name = "bachmoney"
description = "The Stable Foundation decentralized stablecoin platform"
[project]
id = 6
name = "bachmoney"
repository = "bachmoney"
description = "The Stable Foundation"
created_at = "2025-06-29T16:10:20.062Z"
updated_at = "2025-06-29T16:12:15.062Z"